"""add tool call fields to messages

Revision ID: 1c231357b2ff
Revises: 02e25555b27e
Create Date: 2026-09-11 18:14:34.566871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c231357b2ff'
down_revision: Union[str, Sequence[str], None] = '02e25555b27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_call_id', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_calls')
    op.drop_column('messages', 'tool_call_id')
    # ### end Alembic commands ###
