"""add conversation summary_message_id

Revision ID: e7101d6be9d9
Revises: 5bf7ae1148ce
Create Date: 2026-09-13 16:24:45.949213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7101d6be9d9'
down_revision: Union[str, Sequence[str], None] = '5bf7ae1148ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'messages', ['summary_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'summary_message_id')
    # ### end Alembic commands ###
